import {
  AtSign,
  BookOpen,
  Briefcase,
  Calculator,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  CircleHelp,
  Cpu,
  Crown,
  Feather,
  Gem,
  Globe,
  Handshake,
  Hash,
  Landmark,
  Lightbulb,
  Mail,
  Megaphone,
  Mic,
  Microscope,
  Newspaper,
  Palette,
  PenTool,
  Radar,
  Scale,
  Send,
  ShieldAlert,
  Sparkles,
  SquareKanban,
  Star,
  Swords,
  Ticket,
  TrendingUp,
  Trophy,
  UserRound,
  UsersRound,
  type LucideIcon,
} from 'lucide-react'

/** Icons referenced by name in data (roles, templates). */
const ICONS: Record<string, LucideIcon> = {
  AtSign,
  BookOpen,
  Briefcase,
  Calculator,
  CalendarClock,
  CalendarDays,
  ChartColumn,
  CircleHelp,
  Cpu,
  Crown,
  Feather,
  Gem,
  Globe,
  Handshake,
  Hash,
  Landmark,
  Lightbulb,
  Mail,
  Megaphone,
  Mic,
  Microscope,
  Newspaper,
  Palette,
  PenTool,
  Radar,
  Scale,
  Send,
  ShieldAlert,
  Sparkles,
  SquareKanban,
  Star,
  Swords,
  Ticket,
  TrendingUp,
  Trophy,
  UserRound,
  UsersRound,
}

export const ICON_NAMES = Object.keys(ICONS)

export function Icon({ name, className, style }: { name?: string; className?: string; style?: React.CSSProperties }) {
  const Cmp = (name && ICONS[name]) || Sparkles
  return <Cmp className={className} style={style} />
}
